version: "3.9"

services:
  backend:
    build: ./
    container_name: trading-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    ports:
      - "4000:4000"        # ✅ ONLY backend exposed
    networks:
      - internal_net

  mongo:
    image: mongo:6
    container_name: trading-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - internal_net       # ❌ NO ports exposed

  redis:
    image: redis:7
    container_name: trading-redis
    restart: always
    command:
      [
        "redis-server",
        "--appendonly", "no",
        "--bind", "0.0.0.0",
        "--protected-mode", "no"
      ]
    networks:
      - internal_net       # ❌ NO ports exposed

volumes:
  mongo_data:

networks:
  internal_net:
    driver: bridge
